services:
  ollama:
    image: ollama/ollama:latest
    container_name: signalk-ai-bridge-ollama-gemma4
    restart: unless-stopped
    volumes:
      - ./ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 8G
        reservations:
          memory: 2G
#          devices:
#            - driver: nvidia
#              count: 1
#              capabilities: [gpu]
    entrypoint: /bin/sh
    command: -c "ollama serve & sleep 5 && ollama pull gemma4:e2b && wait"
